### ISSUE TITLE
only one thermostat is detected as thermostat, others as binary sensors

### ISSUE THREAD

**Issue by bmeints86** [pwesters/watts_vision#12]
First, thanks for developing this integration. I really like the idea :-)

Oke, I have 3 thermostats in my house, one in the livingroom, one in the kitchen, and one in the office. The thermostat in the office is detected and added as thermostat in homeassistant, however, the other thermostats are only added as sensors, so I cannot control them. Is there any way to change them to thermostats as well? Thanks!

In the debug log, I see the following errors:

2023-12-26 08:21:48.010 ERROR (MainThread) [homeassistant.components.sensor] watts_vision: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 575, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/watts_vision/sensor.py", line 258, in async_update
    self._state = round((int(self._state) - 320) * 5 / 9 / 10, 1)
                         ^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2023-12-26 08:21:48.012 ERROR (MainThread) [homeassistant.components.sensor] watts_vision: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 575, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/watts_vision/sensor.py", line 123, in async_update
    self._state = PRESET_MODE_MAP[smartHomeDevice["gv_mode"]]
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '8'

**Comment by bmeints86** [comment]
Oke, this is fixed! It seems that if the thermostat is programmed to work on a schedule, it is not detected. Once you change the settings to comfort or frost protection, it is detected.
