### ISSUE TITLE
Logs message about turn_on/turn_off methods 

### ISSUE THREAD

**Issue by JackPoint** [pwesters/watts_vision#17]
Thanks for building this integration. It's really helpful for me to automate in combination with a calendar.

The logs show me the following error with the request to report this as a bug

`Entity None (<class 'custom_components.watts_vision.climate.WattsThermostat'>) implements HVACMode(s): heat, cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/pwesters/watts_vision/issues`

There is no more information. Let me know if I can check or test anything to clarify this.

**Comment by JackPoint** [comment]
Looking through the logs I see an error that might be related:

```
Error while setting up watts_vision platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/watts_vision/sensor.py", line 75, in async_setup_entry
    WattsVisionLastCommunicationSensor(
  File "/config/custom_components/watts_vision/central_unit.py", line 16, in __init__
    self._name = "Last communication " + self._label
                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by pwesters** [comment]
Not sure they are related. 

The first I believe is a change in home assistant. See https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/
I need to update the code

In the second for some reason there’s no value for smarthome. I’ll have to look into that and maybe check for null value.

**Comment by Kambara1** [comment]
In Climate.py change line 93 to:
ClimateEntityFeature.TARGET_TEMPERATURE | ClimateEntityFeature.PRESET_MODE | ClimateEntityFeature.TURN_OFF | ClimateEntityFeature.TURN_ON  

Add at the end of the file:
    async def async_turn_off(self) -> None:
        await self.async_set_hvac_mode(HVACMode.OFF)

    async def async_turn_on(self) -> None:
        await self.async_set_hvac_mode(HVACMode.HEAT)
