### ISSUE TITLE
Error setting up Entry for watts_vision. Platform waste_vision.b not found.

### ISSUE THREAD

**Issue by StijnVeer** [pwesters/watts_vision#24]
After updating to 0.4.5 I got the following error:

```
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 23 December 2024 at 17:03:27 (4 occurrences)
Last logged: 07:30:29

Error setting up entry user@email for watts_vision
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/watts_vision/__init__.py", line 37, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, platform)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1123, in async_get_platforms
    if platform := self._get_platform_cached_or_raise(platform_name):
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1214, in _get_platform_cached_or_raise
    raise ModuleNotFoundError(
    ...<2 lines>...
    )
ModuleNotFoundError: Platform watts_vision.b not found
```

After the error none of the thermostats would show any data or load new data. Rolling back to 0.4.4 fixed the issue.

**Comment by Kambara1** [comment]
Yes, 0.4.5 is broken. Issue #20 was fixed incorrectly in this release. Check my latest comment in the #20 and #17 threads.

**Comment by stephenmaij** [comment]
I just tried 0.4.6 and had a similar issue. 
```

2024-12-24 15:28:25.205 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@gmail.com for watts_vision
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/watts_vision/__init__.py", line 35, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, platform)
                                                                ^^^^^^^^
NameError: name 'platform' is not defined. Did you mean: 'Platform'? Or did you forget to import 'platform'?
```
