### ISSUE TITLE
Watts integration not working, NameError. Could you help me with this?

### ISSUE THREAD

**Issue by sentryjack** [pwesters/watts_vision#25]
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 17:14:51 (2 occurrences)
Last logged: 20:42:38

Error setting up entry user@mail.com for watts_vision
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/watts_vision/__init__.py", line 35, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, platform)
                                                                ^^^^^^^^
NameError: name 'platform' is not defined. Did you mean: 'Platform'? Or did you forget to import 'platform'?

**Comment by arjenbos** [comment]
You should be able to downgrade to previous version.

**Comment by Kambara1** [comment]
You can manually change ‘platform’ to ‘PLATFORMS’. @pwesters, the current release is still broken.
